# Generated by Django 5.0.6 on 2024-07-03 23:31

import core.models
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criado em')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Modificado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('rua_avenida', models.CharField(max_length=100, verbose_name='Rua/Avenida')),
                ('preco', models.CharField(max_length=100, verbose_name='Preço')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('imagem', stdimage.models.StdImageField(force_min_size=False, upload_to=core.models.get_file_path, variations={'thumb': {'crop': True, 'height': 256, 'width': 368}}, verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Imóvel',
            },
        ),
    ]
