# Generated by Django 5.0.6 on 2024-07-04 19:47

import core.models
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_imovel'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='aa', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='corretor',
            name='imagem',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to=core.models.get_file_path, variations={'thumb': {'crop': True, 'height': 551, 'width': 1200}}, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='imagem',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to=core.models.get_file_path, variations={'thumb_casas': {'crop': True, 'height': 256, 'width': 368}}, verbose_name='Imagem'),
        ),
    ]
