# Generated by Django 5.0.6 on 2024-07-04 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_imovel_slug_alter_corretor_imagem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovel',
            name='slug',
        ),
    ]
