# Generated by Django 5.0.6 on 2024-07-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_imovel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='', unique=True),
        ),
    ]
